const englishCategoryLabels = {
    electronics: 'Phones & Electronics',
    documents: 'Documents & Identification',
    payments: 'Wallets, Money & Payment Cards',
    bags: 'Bags & Luggage',
    keys: 'Keys & Key Accessories',
    jewelry: 'Jewelry & Watches',
    clothing: 'Clothing & Accessories',
    vehicles: 'Vehicles & Accessories',
    animals: 'Pets & Pet Accessories',
    school: 'Books, School Supplies & Educational Materials',
    professional: 'Musical Instruments, Professional Equipment & Tools',
    personal: 'Personal Items, Children & Leisure'
};

const englishSubcategoryLabels = {
    'electronics:phone': 'Phone / Smartphone', 'electronics:laptop': 'Laptop', 'electronics:desktop': 'Desktop Computer', 'electronics:tablet': 'Tablet', 'electronics:calculator': 'Calculator', 'electronics:smartwatch': 'Smartwatch', 'electronics:earbuds': 'Earbuds', 'electronics:headphones': 'Headphones', 'electronics:camera': 'Camera', 'electronics:camcorder': 'Camcorder', 'electronics:game-console': 'Game Console', 'electronics:mp3-player': 'MP3 Player', 'electronics:external-hard-drive': 'External Hard Drive', 'electronics:usb-drive': 'USB Flash Drive', 'electronics:memory-card': 'Memory Card', 'electronics:charger': 'Charger', 'electronics:cable': 'Cable', 'electronics:powerbank': 'Power Bank', 'electronics:adapter': 'Adapter', 'electronics:router-modem': 'Router / Modem', 'electronics:gps': 'GPS Device', 'electronics:remote-control': 'Remote Control', 'electronics:electronic-accessory': 'Electronic Accessories', 'electronics:other-electronic-device': 'Other Electronic Device',
    'documents:national-id': 'National ID Card', 'documents:passport': 'Passport', 'documents:driving-license': "Driver's License", 'documents:residence-card': 'Residence Permit', 'documents:student-card': 'Student ID Card', 'documents:school-card': 'School ID Card', 'documents:professional-card': 'Work ID / Employee ID', 'documents:electoral-card': 'Voter ID Card', 'documents:administrative-document': 'Administrative Document', 'documents:certificate': 'Certificate / Attestation', 'documents:diploma': 'Diploma', 'documents:administrative-file': 'Administrative File', 'documents:professional-document': 'Professional Document', 'documents:school-document': 'School Document', 'documents:notebook-record': 'Record Book / Booklet', 'documents:other-document': 'Other Document',
    'payments:wallet': 'Wallet', 'payments:purse': 'Coin Purse', 'payments:cash': 'Cash', 'payments:bank-card': 'Bank Card', 'payments:prepaid-card': 'Prepaid Card', 'payments:payment-card': 'Payment Card', 'payments:loyalty-card': 'Loyalty Card', 'payments:transport-card': 'Transport Card', 'payments:cheque': 'Check', 'payments:cheque-book': 'Checkbook', 'payments:card-holder': 'Card Holder', 'payments:other-payment-method': 'Other Payment Method',
    'bags:handbag': 'Handbag', 'bags:backpack': 'Backpack', 'bags:schoolbag': 'School Bag', 'bags:satchel': 'Satchel', 'bags:laptop-bag': 'Laptop Bag', 'bags:briefcase': 'Briefcase', 'bags:suitcase': 'Suitcase', 'bags:carry-on': 'Carry-On Bag', 'bags:travel-bag': 'Travel Bag', 'bags:sports-bag': 'Sports Bag', 'bags:pouch': 'Pouch', 'bags:case': 'Case', 'bags:toiletry-case': 'Toiletry Bag', 'bags:other-bag-luggage': 'Other Bag / Luggage',
    'keys:house-key': 'House Key', 'keys:car-key': 'Car Key', 'keys:motorcycle-key': 'Motorcycle Key', 'keys:keyring': 'Keyring / Set of Keys', 'keys:keychain': 'Keychain', 'keys:access-badge': 'Access Badge', 'keys:gate-remote': 'Gate Remote', 'keys:professional-badge': 'Work ID / Access Badge', 'keys:other-key-accessory': 'Other Key or Accessory',
    'jewelry:ring': 'Ring', 'jewelry:wedding-ring': 'Wedding Ring', 'jewelry:necklace': 'Necklace', 'jewelry:chain': 'Chain', 'jewelry:bracelet': 'Bracelet', 'jewelry:earrings': 'Earrings', 'jewelry:pendant': 'Pendant', 'jewelry:brooch': 'Brooch', 'jewelry:anklet': 'Anklet', 'jewelry:watch': 'Watch', 'jewelry:pocket-watch': 'Pocket Watch', 'jewelry:child-jewelry': "Children's Jewelry", 'jewelry:other-jewelry': 'Other Jewelry',
    'clothing:shirt': 'Shirt', 'clothing:t-shirt': 'T-Shirt', 'clothing:polo': 'Polo Shirt', 'clothing:trousers': 'Trousers / Pants', 'clothing:jeans': 'Jeans', 'clothing:shorts': 'Shorts', 'clothing:skirt': 'Skirt', 'clothing:dress': 'Dress', 'clothing:suit': 'Suit', 'clothing:jacket': 'Jacket', 'clothing:coat': 'Coat', 'clothing:sweater': 'Sweater', 'clothing:sweatshirt': 'Sweatshirt', 'clothing:traditional-outfit': 'Traditional Outfit', 'clothing:uniform': 'Uniform', 'clothing:underwear': 'Underwear', 'clothing:baby-child-clothing': 'Baby / Children\'s Clothing', 'clothing:shoes': 'Shoes', 'clothing:sneakers': 'Sneakers', 'clothing:sandals': 'Sandals', 'clothing:flip-flops': 'Flip-Flops', 'clothing:boots': 'Boots', 'clothing:work-shoes': 'Work Shoes', 'clothing:cap': 'Cap', 'clothing:hat': 'Hat', 'clothing:beanie': 'Beanie', 'clothing:scarf': 'Scarf', 'clothing:headscarf': 'Headscarf', 'clothing:belt': 'Belt', 'clothing:tie': 'Tie', 'clothing:gloves': 'Gloves', 'clothing:glasses': 'Glasses', 'clothing:sunglasses': 'Sunglasses', 'clothing:waist-bag': 'Waist Bag', 'clothing:other-clothing-accessory': 'Other Clothing Accessory',
    'vehicles:car': 'Car', 'vehicles:motorcycle': 'Motorcycle', 'vehicles:scooter': 'Scooter', 'vehicles:tricycle': 'Tricycle', 'vehicles:bicycle': 'Bicycle', 'vehicles:mountain-bike': 'Mountain Bike', 'vehicles:scooter-board': 'Kick Scooter', 'vehicles:other-vehicle': 'Other Vehicle', 'vehicles:motorcycle-helmet': 'Motorcycle Helmet', 'vehicles:license-plate': 'License Plate', 'vehicles:vehicle-key': 'Vehicle Key', 'vehicles:vehicle-remote': 'Vehicle Remote', 'vehicles:vehicle-papers': 'Vehicle Documents', 'vehicles:vehicle-registration': 'Vehicle Registration', 'vehicles:car-accessory': 'Car Accessory', 'vehicles:motorcycle-accessory': 'Motorcycle Accessory', 'vehicles:bicycle-accessory': 'Bicycle Accessory', 'vehicles:other-vehicle-accessory': 'Other Vehicle Accessory',
    'animals:dog': 'Dog', 'animals:cat': 'Cat', 'animals:bird': 'Bird', 'animals:rabbit': 'Rabbit', 'animals:rodent': 'Rodent', 'animals:turtle': 'Turtle', 'animals:other-animal': 'Other Animal', 'animals:pet-collar': 'Pet Collar', 'animals:leash': 'Leash', 'animals:harness': 'Harness', 'animals:cage': 'Cage', 'animals:pet-bed': 'Pet Bed', 'animals:bowl': 'Pet Bowl', 'animals:pet-accessory': 'Pet Accessory',
    'school:book': 'Book', 'school:textbook': 'Textbook', 'school:novel': 'Novel', 'school:notebook': 'Notebook / Exercise Book', 'school:agenda': 'Planner', 'school:school-notebook': 'Notebook', 'school:binder': 'Binder', 'school:school-file': 'School Folder', 'school:pencil-case': 'Pencil Case', 'school:pen': 'Pen', 'school:pencil': 'Pencil', 'school:marker': 'Marker', 'school:ruler': 'Ruler', 'school:school-bag': 'School Bag', 'school:school-calculator': 'School Calculator', 'school:drawing-material': 'Drawing Materials', 'school:geometry-material': 'Geometry Set', 'school:school-supply': 'School Supplies', 'school:other-school-material': 'Other School Material',
    'professional:guitar': 'Guitar', 'professional:piano-keyboard': 'Piano / Keyboard', 'professional:violin': 'Violin', 'professional:drums': 'Drums', 'professional:flute': 'Flute', 'professional:trumpet': 'Trumpet', 'professional:saxophone': 'Saxophone', 'professional:microphone': 'Microphone', 'professional:other-instrument': 'Other Instrument', 'professional:speaker': 'Speaker', 'professional:amplifier': 'Amplifier', 'professional:mixing-console': 'Mixing Console', 'professional:projector': 'Projector', 'professional:video-equipment': 'Video Equipment', 'professional:audio-equipment': 'Audio Equipment', 'professional:tool': 'Tool', 'professional:drill': 'Power Drill', 'professional:construction-equipment': 'Construction Equipment', 'professional:professional-computer': 'Professional Computer Equipment', 'professional:office-equipment': 'Office Equipment', 'professional:medical-equipment': 'Medical Equipment', 'professional:laboratory-equipment': 'Laboratory Equipment', 'professional:commercial-equipment': 'Commercial Equipment', 'professional:industrial-equipment': 'Industrial Equipment', 'professional:other-professional-equipment': 'Other Professional Equipment',
    'personal:umbrella': 'Umbrella', 'personal:water-bottle': 'Water Bottle', 'personal:bottle': 'Bottle', 'personal:thermos': 'Thermos', 'personal:cosmetics': 'Cosmetics', 'personal:care-product': 'Personal Care Product', 'personal:brush-comb': 'Brush / Comb', 'personal:toiletry-kit': 'Toiletry Bag', 'personal:personal-medical': 'Personal Medical Item', 'personal:personal-accessory': 'Personal Accessory', 'personal:other-personal-object': 'Other Personal Item', 'personal:toy': 'Toy', 'personal:stuffed-animal': 'Stuffed Animal / Plush Toy', 'personal:stroller': 'Stroller', 'personal:baby-bottle': 'Baby Bottle', 'personal:diaper-bag': 'Diaper Bag', 'personal:baby-accessory': 'Baby Accessory', 'personal:child-accessory': 'Children\'s Accessory', 'personal:ball': 'Ball', 'personal:jersey': 'Jersey', 'personal:sports-shoes': 'Sports Shoes', 'personal:racket': 'Racket', 'personal:fitness-equipment': 'Fitness Equipment', 'personal:sports-equipment': 'Sports Equipment', 'personal:board-game': 'Board Game', 'personal:video-game': 'Video Game', 'personal:collectible': 'Collectible Item', 'personal:collection-album': 'Collection Album', 'personal:leisure-equipment': 'Leisure Equipment', 'personal:travel-item': 'Travel Item', 'personal:other-sport-item': 'Other Sports Item', 'personal:other-leisure': 'Other Leisure Item', 'personal:tableware': 'Tableware', 'personal:utensil': 'Utensil', 'personal:small-appliance': 'Small Household Appliance', 'personal:decoration': 'Decorative Item', 'personal:kitchen-item': 'Kitchen Item', 'personal:household-item': 'Household Item', 'personal:craft-object': 'Craft Item', 'personal:religious-object': 'Religious Item', 'personal:other-domestic-object': 'Other Household Item', 'personal:unidentified-object': 'Unidentified Item', 'personal:miscellaneous-object': 'Miscellaneous Item', 'personal:other-object': 'Other'
};

module.exports = { englishCategoryLabels, englishSubcategoryLabels };
